fos_rest:
  format_listener:
    rules:
      - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
      - { path: '^/', priorities: ['html'], fallback_format: html, prefer_extension: false }
  view:
    formats:
      json: true
    view_response_listener: 'force'
